<?php
/**
 * @author Magebees Team
 * @copyright Copyright (c) Magebees (https://www.magebees.com)
 * @package Full Page Cache Warmer for Magento 2
 */
/** @var \Magebees\CacheWarmer\Block\Status $block */
/** @var \Magento\Framework\Escaper $escaper */

$notCacheable = $block->getNotCacheableBlocks();
$showContextData = $block->isContextDataDebug();
?>

<div class="magebees-cachewarmer-crawler-status status-<?= $escaper->escapeHtmlAttr($block->getStatusCode()) ?>">
    <div class="status-header">Full Page Cache</div>
    <div class="status"><?= $escaper->escapeHtml($block->getStatusTitle()) ?></div>
    <?php if ($notCacheable): ?>
        <div class="not-cacheable">
            <div class="not-cacheable-header"><?= $escaper->escapeHtml(__('Not cacheable blocks')) ?></div>
            <div class="blocks">
                <?php foreach ($notCacheable as $blockData): ?>
                    <div class="not-cacheable-block">
                        <div class="name"><?= $escaper->escapeHtml($blockData['name']) ?></div>
                        <div class="class"><?= $escaper->escapeHtml($blockData['class']) ?></div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif ?>
    
</div>
