<!-- Styles -->
<style>
#barchartdiv {
  width: 100%;
  height: 500px;
}

</style>

<?php 
$warmerLogData=$this->warmerLogFactory->create()->getCollection()->getData();
$chart_array=[];
$date_count=[];
if(!empty($warmerLogData))
{
foreach($warmerLogData as $data)
{
	$date=$this->dateFormat($data['created_at']);
	
  $date_count[]=$date;
}
$datewise_data=array_count_values($date_count);

foreach($datewise_data as $sdate=>$urlCount )
{
	$formattedDate=$this->dateTextFormat($sdate);
	$chart_array[]=array("Date" => $formattedDate, "pageCount" => $urlCount);
}

}
$chart_array_encode=json_encode($chart_array);

?>
<?php if(!empty($chart_array)): ?>
<script>
// LOAD DEPENDENCIES; CREATE CHART
require(['amcharts', 'amcharts.serial'], function(AmCharts, AmChartsSerial) {
	 var barChartData=<?php echo $chart_array_encode; ?>;
var chart = AmCharts.makeChart("barchartdiv", {
	"type": "serial",
	"pathToImages": "http://cdn.amcharts.com/lib/3/images/",
	"categoryField": "Date",
	"rotate": false,
	"startDuration": 1,
    "legend":
      {
        "useGraphSettings": true
      },
	"categoryAxis": {
		"gridPosition": "start",
		"position": "left",
        "autoGridCount": false,
        "gridCount": 23
	},
	"trendLines": [],
	"graphs": [		
        {
			"balloonText": "Warmed Pages Qty on [[Date]]: [[value]]",
			"fillAlphas": 0.8,
			"id": "AmGraph-1",
			"lineAlpha": 0.2,
            "lineColor": "#0000AA",
			"title": "Warmed Pages Qty",
			"type": "column",
			"valueField": "pageCount"
		}
	],
	"guides": [],
	"valueAxes": [
		{
			"id": "ValueAxis-1",
			"position": "top",
			"axisAlpha": 0
		}
	],
	"allLabels": [],
	"amExport": {
		"right": 20,
		"top": 20
	},
	"balloon": {},
	"titles": [],
	"dataProvider": barChartData
});

  // ERROR HANDLER
}, function(err) {
  console.log('Something went wront: ', err);
});
</script>
<?php else: ?>
  <div>Sorry, There is no data available.</div>
<?php endif; ?>
<!-- HTML -->
<div id="barchartdiv"></div>